# Generated by Django 5.0.4 on 2024-04-20 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_alter_dadosmedico_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasabertas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medico.dadosmedico'),
        ),
    ]
